/* Generated by oas2sadl */

//
// test2 - originally in oasv3
//
name test2
version "v1"

type CarrierInfo Struct {
   shipmentType String (values=["SPD","LTL"])
   carrierId String
   scac String
   carrierName String
}


