package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"io/ioutil"
	"os"
	"strings"

	"github.com/boynton/sadl"
	"github.com/boynton/sadl/smithy"
)

var verbose bool = false

func main() {
	pDebug := flag.Bool("d", false, "set to true to enable debug output")
	pVerbose := flag.Bool("v", false, "set to true to enable verbose output")
	flag.Parse()
	args := flag.Args()
	if len(args) != 1 {
		fmt.Println("usage: smithy2sadl [-v] file")
		os.Exit(1)
	}
	verbose = *pVerbose
	path := args[0]
	name := path
	n := strings.LastIndex(name, "/")
	if n >= 0 {
		name = name[n+1:]
	}
	n = strings.LastIndex(name, ".")
	if n >= 0 {
		name = name[:n]
		name = strings.Replace(name, ".", "_", -1)
	}
	var ast *smithy.AST

	data, err := ioutil.ReadFile(path)
	if err != nil {
		fmt.Printf("smithy2sadl: Cannot read source file: %v\n", err)
		os.Exit(1)
	}
	if strings.HasSuffix(path, ".json") {
		err = json.Unmarshal(data, &ast)
		if err != nil {
			fmt.Printf("smithy2sadl: Cannot parse source file: %v\n", err)
			os.Exit(1)
		}
		ns := ""
		model := smithy.NewModel(ast, name, ns)
		sadlModel, err := model.ToSadl()
		if err != nil {
			fmt.Printf("smithy2sadl: Cannot convert to SADL: %v\n", err)
			os.Exit(1)
		}
		if *pDebug {
			fmt.Println(sadl.Pretty(sadlModel)) //debug
		} else {
			fmt.Println("/* Generated by smithy2sadl */\n\n" + sadl.Decompile(sadlModel))
		}
	}
}
